name: smartmeter

networks:
  smartmeter-network:
    driver: bridge

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management, rabbitmq_stream_management, rabbitmq_stream]."

services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-service
    restart: always
    networks:
      - smartmeter-network
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  # UI Service
  clientui:
    image: client-ui:latest
    container_name: ui
    restart: unless-stopped
    networks:
      - smartmeter-network
    ports:
      - "80:80"

  # API Service
  clientserver:
    image: client-server:latest
    container_name: client
    restart: unless-stopped
    networks:
      - smartmeter-network
    environment:
      HMAC: 00deb39aaf33c17977e0c858148dca5483703f554da146637b35914772cae5b2
      RabbitMQAddress: rabbitmq-service
    ports:
      - "3000:3000"
    volumes:
      - ./apps/server/config:/app/config
