services:
  ingestion:
    image: ingestion:latest
    container_name: ingestion_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      HMACKEY: 00deb39aaf33c17977e0c858148dca5483703f554da146637b35914772cae5b2
      CLIENTFW: 1.0.0
    volumes:
      - ./src/ingestion.conf:/app/src/ingestion.conf
    command: ["/usr/local/bin/ingestion"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # message port
      - "15672:15672"    # management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: