name: smart-meter-gateway-local

networks:
  smartmeter-network:
    driver: bridge

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management, rabbitmq_stream_management, rabbitmq_stream]."

services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-service
    restart: always
    networks:
      - smartmeter-network
    ports:
      - 5552:5552
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  # Gateway Service
  gateway:
    image: gateway:latest
    container_name: gateway
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9002:9002/udp"
    networks:
      - smartmeter-network
    environment:
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/%2F
      EXCHANGE_NAME: ddes.readings
      ROUTING_KEY: billing
      QUEUE_SIZE: 1024
      ALERT_URL: "http://client:3000/alert"
      HELLO_WORLD_URL: "http://client:3000/hello-world"
