users:
  user1:
    name: Alice
    role: admin
    password: secret
  user2:
    name: Bob
    role: user
    password: password123
  user3:
    name: Charlie
    role: user
    password: charliepwd
  user4:
    name: Diana
    role: user
    password: dianapass
  user5:
    name: Eve
    role: user
    password: eve2024
  user6:
    name: Frank
    role: user
    password: frankie
  user7:
    name: Grace
    role: user
    password: graceful
  user8:
    name: Heidi
    role: user
    password: heidipwd
  user9:
    name: Ivan
    role: user
    password: ivan123
  user10:
    name: Judy
    role: user
    password: judypass
  user11:
    name: Karl
    role: user
    password: karl2024
  user12:
    name: Laura
    role: user
    password: lauralove
