name: smart-meter

networks:
  smartmeter-network:
    driver: bridge

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management, rabbitmq_stream_management, rabbitmq_stream]."

services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-service
    restart: always
    networks:
      - smartmeter-network
    ports:
      - 5552:5552
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
  # UI Service
  ui:
    image: client-ui:latest
    container_name: ui
    restart: unless-stopped
    networks:
      - smartmeter-network
    ports:
      - "80:80"
  # API Service
  client:
    image: client-server:latest
    container_name: client
    restart: unless-stopped
    networks:
      - smartmeter-network
    environment:
      HMAC: 00deb39aaf33c17977e0c858148dca5483703f554da146637b35914772cae5b2
      RabbitMQAddress: rabbitmq-service
    volumes:
      - ./client/apps/server/config:/app/config
  # Ingestion Service
  ingestion:
    image: ingestion:latest
    restart: unless-stopped
    container_name: ingestion
    networks:
      - smartmeter-network
    environment:
      HMACKEY: 00deb39aaf33c17977e0c858148dca5483703f554da146637b35914772cae5b2
      CLIENTFW: 1.0.0
    volumes:
      - ./src/ingestion.conf:/app/src/ingestion.conf
    command: ["/usr/local/bin/ingestion"]
  # Billing Service
  billing:
    image: billing:latest
    container_name: billing-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_HOST=rabbitmq-service
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    networks:
      - smartmeter-network
  # Gateway Service
  gateway:
    image: gateway:latest
    container_name: gateway
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9002:9002/udp"
    networks:
      - smartmeter-network
    environment:
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/%2F
      EXCHANGE_NAME: ddes.readings
      ROUTING_KEY: billing
      QUEUE_SIZE: 1024
      ALERT_URL: "http://client:3000/alert"
      HELLO_WORLD_URL: "http://client:3000/hello-world"
