services:
  # UI Service
  clientui:
    image: client-ui:latest
    restart: unless-stopped
    ports:
      - "8080:80"

  # API Service
  clientserver:
    image: client-server:latest
    restart: unless-stopped
    environment:
      - HMAC=00deb39aaf33c17977e0c858148dca5483703f554da146637b35914772cae5b2
    ports:
      - "3000:3000"
